### ISSUE TITLE
Tutorial video improvements

### ISSUE THREAD

**Issue by ugurdogrusoz** [iVis-at-Bilkent/software-artifact-analyzer#119]
Overall it looks real good. Developer recommendation example is excellent. Here are some improvement suggestions.

- [x] 1. Let's place line breaks more evenly (roughly half-half or where it logically breaks). Example: "... GitHub and" & "Jira ..."
![image](https://github.com/iVis-at-Bilkent/software-artifact-analyzer/assets/3874988/866e3ff6-c3d8-469e-a77b-aea33c966025)

- [x] 2. We have long pauses very frequently, we should reduce these pauses significantly

- [x] 3. N-e-o-4-j instance: any way we can dictate the right pronunciation here?

- [x] 4. Set up is still 1 and a half minutes which is too long I think. Get rid of pauses, don't show all details, skip redundant user, date filtering, etc.

- [x] 5. We keep saying "artifacts and developers". Developers could very well be considered software artifacts (after all they are in the software artifact graphs). We shouldn't make such a distinction. This should make the dictations shorter as well.

- [x] 6. One big criticism we got as feedback was people do not like to go out of their comfort zone of using GitHub & Jira. Hence, we placed "hooks" from GitHub and Jira issues inside comments. But starting at 1:30 we still show the user how to start visual analysis from within SAA as opposed to GitHub and Jira and for a very long time we stay within/inside SAA. We should change this. At least in the beginning, we should launch SAA from within GitHub and Jira.

- [x] #121
![image](https://github.com/iVis-at-Bilkent/software-artifact-analyzer/assets/3874988/5adc2d5e-aaa3-4e7a-815f-810bd3acfcbd)

- [x] 8. At around 5:00, when we give an example of reviewer recommendation, we repeat the meaning of options such as "Adjust developer size" and "Graph". This is unnecessary.

- [x] 9. "11 different anomalies" => "numerous types of anomalies"

- [x] 10. Let's avoid stating the obvious. Example: at 6:15, "users can navigate to the Database ..." They already see these.

- [x] #129

- [x] 12. Finally, we could conclude with a statement like, we hope you'll find SAA to ...

**Comment by eraytuzun** [comment]
The video looks great, thanks
One minor comment at the end of the demo we can also provide a link to the tool webpage

**Comment by ugurdogrusoz** [comment]
The video is again outstanding. Some minor improvements:
- [ ] 20. 0:56: "... the pull request in the GitHub ..." => "... pull requests in the GitHub ..."
- [ ] 21. 1:21, 1:24: "the SAA" => "SAA"
- [ ] 22. 3:29: "cluster results" => "clustering results"
- [ ] 23. 4:20: "We utilize a method called RSTrace+ ..." => "SAA uses the latest software analytics research results to aid visual analysis. For example, we utilize a method called RSTrace+ ..."
- [ ] 24. 7:33: "issuesare" => "issues are"
- [ ] 25. 7:41: When scanned, it says QR code has been disabled! I assume this points to the sample deployment.
- [ ] 26. Let's consistently use the same shape to highlight parts of the screen (as opposed to rectangle, rounded rectangle, ellipse in different places). I would prefer this sketch like one at 1:05.
- [ ] 27. To emphasize how SAA is based on latest scientific publications, let's also cite the paper on anomaly detection in the related section.

**Comment by LaraMerdol** [comment]
- Change the subtitles for subtasks 20, 21, and 22.
- Add a part to subtask 23.
- Fix the typo in subtask 24.
- Generate a new QR code for subtask 25.
- Regarding subtask 26, if it's acceptable and not too troublesome, I recommend discarding it as making the necessary changes would be time-consuming.
- Subtask 27 has been updated with the added part.
New Tutorial: 
[tutorial](https://drive.google.com/file/d/1iIJBPyZUi5hljCevabmdcSJaNU3ly4N8/view?usp=sharing)

**Comment by ugurdogrusoz** [comment]
we have this left: "pull request => pull requests" but it's OK (nazarlik)
