### ISSUE TITLE
Make SAA public

### ISSUE THREAD

**Issue by LaraMerdol** [iVis-at-Bilkent/software-artifact-analyzer#123]
We have decided to publish SAA publicly. Now saa is also accessible from [http://saa.cs.bilkent.edu.tr/](http://saa.cs.bilkent.edu.tr/). One problem is that ngix is not allowed to serve bolt protocol. Therefore, we couldn't enable users to build graphs without the VPN connection.

**Comment by saanalyzer** [comment]
I changed the ownership of the Github app and Atlassian app to Saanlyzer accounts. I also updated autopull.sh to use Saanlyzer Github credentials. The installation process for the Github app should remain the same start from  Github.

......cOUNTUNIE

**Comment by LaraMerdol** [comment]
<img width="1144" alt="Screen Shot 2024-07-18 at 16 26 42" src="https://github.com/user-attachments/assets/566539a5-cb7e-4c32-9807-71c867d60cd0">

**Comment by LaraMerdol** [comment]
We can close this issue if it's okay. We have opened a new issue for the test flow. If there are any other problems, we can continue from there. #149

**Comment by ugurdogrusoz** [comment]
@LaraMerdol please create a Google doc that contains all account and password information (that you had shared with us earlier) for all subscriptions, accounts, etc. and share it with @eraytuzun and me (only the three of us should have access to this document). Thanks

**Comment by LaraMerdol** [comment]
**Documents containing important credentials of Saanlyzer User:** https://docs.google.com/document/d/1l9cQmTIoYxpjKPPPdDUVZ-x3GbpFz1a1p6or6VDB_DM/edit?usp=sharing. (only accessible by  @eraytuzun  and @ugurdogrusoz )
