### ISSUE TITLE
Display Issue Types in Node UIs

### ISSUE THREAD

**Issue by LaraMerdol** [iVis-at-Bilkent/software-artifact-analyzer#140]
Show issue types in node UIs and enable special filtering for them. Choose appropriate badges for that.

**Comment by LaraMerdol** [comment]
Subtask 6 fixed: Changed according to the feedback.
<img width="319" alt="Screen Shot 2024-07-15 at 23 38 01" src="https://github.com/user-attachments/assets/6fc523fd-e425-4cdc-8ea0-77510f06291a">
Subtask 5 fixed: Now, if the theoretical property badge and anomaly detection badges are clicked, the anomaly badge will appear in the right corner. Additionally, the anomaly badge size will change to match the issue node size.
![Screen Recording 2024-07-15 at 23 27 46](https://github.com/user-attachments/assets/f8250e59-5e91-4f45-bf9d-012d30fb65de)
If the anomaly badge is clicked, the theoretical properties anomaly badges swap to the right position, and the size is updated to be scaled with the new anomaly size.
![Screen Recording 2024-07-15 at 23 37 20](https://github.com/user-attachments/assets/db225288-30b3-4737-bab7-555455ac7c17)

**Comment by ugurdogrusoz** [comment]
This issue is clutter. I am closing this and opening a new one with any remaining problems.
