### ISSUE TITLE
Context menu: New queries can be added to enhance the drawing canvas use

### ISSUE THREAD

**Issue by LaraMerdol** [iVis-at-Bilkent/software-artifact-analyzer#146]
Suggestions;

1. Show the committed developer for the pull request
2. Currently, there are two relations labeled as referenced, one for referenced commits and the other for referenced pr. Maybe adding separate queries for other artifacts would be more beneficial. Currently, for other artifacts, referenced relations only gather referenced commits. For example, when we want to gather referenced issues related to a code file, it only checks if any commit includes the file referenced as an issue and vice versa for issues to files.
3.

**Comment by LaraMerdol** [comment]
New queries added to the context menu:

1. Committed developer for the pull request

![Screen Recording 2024-07-17 at 01 50 26](https://github.com/user-attachments/assets/e4024512-bc1a-4ee1-ad09-7c6f075cb952)

2. As mentioned before, there are currently two relations: one between issue and pull request (PR), and the other between issue and commit. We have named these relations as REFERENCED_COMMIT and REFERENCED_PR, both having the same label "reference." The issue we're facing is that the context menu structure provided by Visual Studio does not allow for both multi-length and multi-path queries. Therefore, we need to separate the relations required to use reference relations, such as files related to issues can pass from file-commit-PR-issue or file-commit-issue. I have added separate items for those cases named "Commit" and "Pull Request."
  **For issue context menu:**
  - Committing developers (recent, show, hide)
  - Related files (recent, show, hide)
  
![Screen Recording 2024-07-17 at 02 00 56](https://github.com/user-attachments/assets/999cc2d4-e7ac-4394-85f8-4cb92d843b13)

**Comment by LaraMerdol** [comment]
I couldn't fix the problem with the server. If the data doesn't come through, you can go to the `'/visual/software-artifact-analyzer-configuration' `directory on the server and manually start runner.sh again. Currently it is working. 

`sudo ./runner.sh &
`

**Comment by ugurdogrusoz** [comment]
We (@gorkemsolun) are having problems with another Visuall and Neo4j based tool lately. I wonder if a DB error on that tool might be breaking SAA's DB?

**Comment by ugurdogrusoz** [comment]
This is from PR's context menu:
<img width="620" alt="Screenshot 2024-07-16 at 21 24 45" src="https://github.com/user-attachments/assets/359505b2-304d-407b-ac1c-41fd6d8f43d8">

When we say "Show Issues Recently Referenced", do we mean **issues referenced by the PR** or vice versa: **issues referencing the P**? If the latter we should rename these as:
- Show Recently Referencing Issues
- Show Referencing Issues
- Hide Referencing Issues

**Comment by LaraMerdol** [comment]
We check if "pr" is referenced by the issue, so we should change the naming as you suggest.
Naming changed according to the feedback for commit and pr content menu.
**Commit:**
<img width="428" alt="Screen Shot 2024-07-17 at 09 55 40" src="https://github.com/user-attachments/assets/a6e2670a-fd9e-490c-9875-bb7685b96559">
**Pr:**
<img width="497" alt="Screen Shot 2024-07-17 at 09 56 05" src="https://github.com/user-attachments/assets/bc1c51bf-0a36-4991-9f84-8bb049ff9cac">
