### ISSUE TITLE
Web page and README improvements

### ISSUE THREAD

**Issue by ugurdogrusoz** [iVis-at-Bilkent/software-artifact-analyzer#150]
Let's improve these two as follows:

- Keep the following in README but remove from the web page: Running a local instance, Credits to Maintenance (inclusive)
- Let's keep the introductory statement in both
- Let's keep the screenshot redundantly in both
- Put a link from README saying "SAA web page including instructions on usage and customization may be found [here](https://ivis-at-bilkent.github.io/software-artifact-analyzer/)"

For the web page:
- Let's *embed* (not just a link - [example](https://newteditor.org/tutorials-basics.html)) the demo link to YouTube (currently don't have this obviously)
- Let's enrich it with the usage of the tool (like the planned implications for practitioners and researchers section in the paper)
- More screenshots explaining each of the 3 use cases / applications

**Comment by LaraMerdol** [comment]
Page updated : https://ivis-at-bilkent.github.io/software-artifact-analyzer/index.html 

ReadME: Updates: https://github.com/iVis-at-Bilkent/software-artifact-analyzer/tree/master?tab=readme-ov-file

**Comment by ugurdogrusoz** [comment]
This is done pending the update of the video tutorial.

**Comment by ugurdogrusoz** [comment]
All completed now
