### ISSUE TITLE
Enrich default timebar statistics

### ISSUE THREAD

**Issue by ugurdogrusoz** [iVis-at-Bilkent/software-artifact-analyzer#151]
Let's enrich the default timebar statistics as discussed in our previous meeting.

**Comment by LaraMerdol** [comment]
<img width="363" alt="Screen Shot 2024-07-25 at 17 37 53" src="https://github.com/user-attachments/assets/2c76cdc5-b6fb-470a-a22b-da81b63d1a1d">

**Comment by LaraMerdol** [comment]
Change naming according to the feedback. 
![Screen Recording 2024-07-26 at 10 42 58](https://github.com/user-attachments/assets/b3fff618-818c-4d4f-b328-065fc520be79)

**Comment by LaraMerdol** [comment]
<img width="352" alt="Screen Shot 2024-07-26 at 10 44 08" src="https://github.com/user-attachments/assets/cc06d28b-5d5e-40cb-b236-7fd5d1451f8f">

**Comment by LaraMerdol** [comment]
<img width="335" alt="Screen Shot 2024-07-26 at 10 45 30" src="https://github.com/user-attachments/assets/84bec8f4-ca5b-4d01-a9a7-cdf910d77e57">
