### ISSUE TITLE
Demo edition related changes

### ISSUE THREAD

**Issue by ugurdogrusoz** [iVis-at-Bilkent/software-artifact-analyzer#153]
Since our demo edition is a shared DB one for all people who would like to try SAA, we need to do the following:
- [x] 1. The code should somehow differentiate between a deployment on our server and a deployment by users (local deployment). When it's a demo deployment on our server (i.e., http://saa.cs.bilkent.edu.tr/), we should disable constructing a new project and provide a text along these lines instead of the usual wizard: "This is a shared database demo version of SAA and creating a new project from your own repositories is disabled. For the same reason, you will not be able to use certain other functionality such as reporting on GitHub and Jira and assigning reviewers to a particular Pull Request directly from SAA." Let's also provide some information about what this sample project is that they will be trying the demo with.
- [x] 2. In this demo edition, warn the user when they try to do operations that they aren't allowed. 
- [x] 3. In GitHub repository's README, make sure "Running a Local Instance" is updated to do the necessary configurations.

**Comment by LaraMerdol** [comment]
**Open new project:**
<img width="1017" alt="Screen Shot 2024-07-27 at 23 17 37" src="https://github.com/user-attachments/assets/2daa4a71-de58-4f75-9e4f-0382b844f3c1">

**Report:**
<img width="1025" alt="Screen Shot 2024-07-27 at 23 18 25" src="https://github.com/user-attachments/assets/fc0d796d-8085-4c1d-84ba-f93e8cc634ab">

**Reviever Assign:**
<img width="1044" alt="Screen Shot 2024-07-27 at 23 19 12" src="https://github.com/user-attachments/assets/c8da9216-d35d-4ee1-98db-68d6c63ba663">

**Comment by LaraMerdol** [comment]
software-artifact-analyzer  3:
Added
<img width="1151" alt="Screen Shot 2024-07-27 at 23 20 57" src="https://github.com/user-attachments/assets/ead58250-e853-4fad-834a-94199b9e4927">
