### ISSUE TITLE
Release SAA as version 1.0.0

### ISSUE THREAD

**Issue by ugurdogrusoz** [iVis-at-Bilkent/software-artifact-analyzer#154]
as planned with the same numbered milestone and described [here](https://docs.github.com/en/repositories/releasing-projects-on-github/managing-releases-in-a-repository#creating-a-release)
Prior to this, let's:
- Do a final round of testing
- Merge `unstable` branch to `master`
- Then do the release out of the `master` branch

**Comment by LaraMerdol** [comment]
Tests:
Main Features:
- [ ] Expert Recommendations
- [ ] Reviewer Recommendations
- [ ] Anomaly Detection
- [ ] Anomaly Statistics

**Comment by LaraMerdol** [comment]
@ugurdogrusoz subtask 1,2,3,4,5,6
@LaraMerdol  subtask 7,8,9,10,11,12

**Comment by LaraMerdol** [comment]
###  7. Custom queries

- [ ] All queries input filtering works.
![Screen Recording 2024-07-30 at 14 56 13](https://github.com/user-attachments/assets/00834013-b761-421c-942f-12a14439c1be)
- [ ] Result and page limiting works fine.
![Screen Recording 2024-07-30 at 14 58 27](https://github.com/user-attachments/assets/c034cb63-aa82-4044-a3c6-ef3251eaac5e)

- [ ] Graph result, merge, not merge hover works fine.
![Screen Recording 2024-07-30 at 15 00 42](https://github.com/user-attachments/assets/9e9a2100-be65-45f3-81f1-b52a980de698)

- [ ] Text result graph selected works fine

![Screen Recording 2024-07-30 at 15 02 12](https://github.com/user-attachments/assets/00f8690d-f43c-4b39-a352-0a8baf561e19)

**!!ISSUE:** Sometimes the first click on the execute does not produce a graph result. A second click is required.
![Screen Recording 2024-07-30 at 14 50 27](https://github.com/user-attachments/assets/81f947bd-c705-4ca0-8ada-8a9a99beab36)

**Comment by LaraMerdol** [comment]
### 8. Settings
Hovering and selecting add label soon works fine. 
![Screen Recording 2024-07-31 at 10 31 05](https://github.com/user-attachments/assets/919c2518-e956-439a-88c5-2e839c77c070)
Grouping options works fine
![Screen Recording 2024-07-31 at 10 33 30](https://github.com/user-attachments/assets/dce8b14d-81e7-4b86-b59b-6f900392f92f)
Page limit vs. works fine
![Screen Recording 2024-07-31 at 10 34 39](https://github.com/user-attachments/assets/a232ac98-3c7c-4547-bce2-d9f8822eb1d3)

**Comment by LaraMerdol** [comment]
### 9. Expert Recommendations
## Test Flow: Select a File and Execute Object Queries
1. Select a file from the drawing canvas.
2. Open object queries and request expert recommendation.
3. Execute work graph result and cluster.
4. Add badges.
5. Remove clustering and badges.
6. Add clustering and badges again.
7. Close graph result.
8. Request 4 recommendations.
9. Add the last recommendation as a merge. 
![Screen Recording 2024-07-31 at 10 54 34](https://github.com/user-attachments/assets/ad98ca2b-ad4c-40e1-a293-8ed5be4fd96f)
## Test Flow: Execute Custom Queries and Select a File
1. Open custom queries.
2. Select a file from the file list.
3. Execute query for max number of developers (5).
![Screen Recording 2024-07-31 at 11 01 31](https://github.com/user-attachments/assets/789205f2-cf6d-4f92-98e6-05996f768724)

!!!One problem is with small scores, as we let two decimals be seen as 0. However, we have discussed this issue and decided to leave it as it is.

**Comment by LaraMerdol** [comment]
### Reviewer Recommendations
Same test flows as expert recommendation also repeated. 
I have also checked the output result filtering.
![Screen Recording 2024-07-31 at 11 11 52](https://github.com/user-attachments/assets/305a84ca-8739-4f2e-bedc-006b3d327e3b)
And for reviewer recommendations in the demo version, it should not allow the assignment of a reviewer.
<img width="793" alt="Screen Shot 2024-07-31 at 11 13 35" src="https://github.com/user-attachments/assets/b6465dba-c7cb-4cfe-a5d3-8e4aa14d8f30">

**Comment by LaraMerdol** [comment]
###  11. Anomaly Detection
Anomaly settings have been tested in test case 8 and were included in the settings testing.
Minor issue fixed related to missing issue priority. Now it also shows another badge
<img width="1484" alt="Screen Shot 2024-07-31 at 11 54 32" src="https://github.com/user-attachments/assets/f85e332f-85bc-4442-a406-98232f0853e1">
All issues, anomalies, and fields were checked. I could not find any problems. 

###  12. Anomaly Statistics
Anomaly statistics have been checked, and no visible problems have been found. In addition, badges have been issued at each step. Anomalies have been counted from 1 to 6. No issue has more than 6 anomalies.
