### ISSUE TITLE
Simplify the root folder in sources

### ISSUE THREAD

**Issue by ugurdogrusoz** [iVis-at-Bilkent/software-artifact-analyzer#158]
Move files in the root folder to appropriate folders (create new one(s) as needed).
Make sure the scripts to rebuild are appropriately changed.
![image](https://github.com/user-attachments/assets/13336c87-61fa-4961-a523-25774a926eda)

**Comment by LaraMerdol** [comment]
The root folder has been simplified as requested to improve organization and maintainability. Key changes include:

Script Organization: All scripts previously located in the root directory have been moved to a new dedicated folder named scripts/. This change helps declutter the root folder and provides a centralized location for all automation and utility scripts (e.g., autopull.sh, runner.sh).

E2E Test Files: End-to-end (E2E) test-related files, which were previously scattered, have been grouped together within the same scripts/ folder.
