### ISSUE TITLE
Possible Bug: All Developers List is not Updated

### ISSUE THREAD

**Issue by idilhanhan** [iVis-at-Bilkent/software-artifact-analyzer#54]
When I confirm the similarity selections and move to the next step, which is **All Developers**, I see a list of developers according to my previous selections. This can be seen below.

<img width="970" alt="Screenshot 2023-12-22 at 17 00 20" src="https://github.com/iVis-at-Bilkent/software-artifact-analyzer/assets/27965453/144feba4-8d6c-45c9-ae8c-61e6abeff080">

However, when I go back and change my selection, I can still see the previous list of developers and the new selections I made are added on top of them.

<img width="972" alt="Screenshot 2023-12-22 at 17 01 50" src="https://github.com/iVis-at-Bilkent/software-artifact-analyzer/assets/27965453/ca5771c7-468b-4dd1-aed9-9c0f95d096c8">
<img width="971" alt="Screenshot 2023-12-22 at 17 02 02" src="https://github.com/iVis-at-Bilkent/software-artifact-analyzer/assets/27965453/53a51bcb-1bad-4e23-b7f0-69dc95819e50">

I expected to see the list that reflects the most recent selections. However, this could just be a different design choice so please feel free to close this if that is indeed the case.

**Comment by LaraMerdol** [comment]
The issue has been completed!
