### ISSUE TITLE
Suggestion: Query for None date

### ISSUE THREAD

**Issue by idilhanhan** [iVis-at-Bilkent/software-artifact-analyzer#78]
I wanted to run a query to highlight the issues that are yet to be closed but was not able to select `None` or an empty value for the `closedDate` field while constructing the query.

<img width="331" alt="Screenshot 2024-01-02 at 21 05 44" src="https://github.com/iVis-at-Bilkent/software-artifact-analyzer/assets/27965453/b7f43b86-aaaf-4605-a994-e9e16ee2a02b">

**Comment by LaraMerdol** [comment]
This issue has been completed!
