### ISSUE TITLE
Bug: Query by title results not highlighted for issues

### ISSUE THREAD

**Issue by idilhanhan** [iVis-at-Bilkent/software-artifact-analyzer#79]
I constructed a query that looks for issue nodes that contain `bug` in the title. After executing the query none of the nodes were highlighted. 

<img width="968" alt="Screenshot 2024-01-02 at 21 11 09" src="https://github.com/iVis-at-Bilkent/software-artifact-analyzer/assets/27965453/dadc28af-9dcd-4272-925e-c2e5a980e64a">

But as it can be seen below, there is at least one issue that has `bug` in the title. 

<img width="217" alt="Screenshot 2024-01-02 at 21 09 35" src="https://github.com/iVis-at-Bilkent/software-artifact-analyzer/assets/27965453/316a8ba1-9044-490a-9b2d-8c31d6d91688">

I don't think this is related to case sensitivity because I had the same issue with `fixing` as well.

<img width="947" alt="Screenshot 2024-01-02 at 21 08 09" src="https://github.com/iVis-at-Bilkent/software-artifact-analyzer/assets/27965453/09e31904-4dc2-4022-bd01-d505784ca4af">

But the query did work with `problem`. I'm not sure if this is related to the location of the string we are looking for in the title, or maybe this was a temporary issue caused by running queries back to back.

<img width="943" alt="Screenshot 2024-01-02 at 21 10 18" src="https://github.com/iVis-at-Bilkent/software-artifact-analyzer/assets/27965453/41c1e98a-012b-4863-97c2-ce48fe74ab24">

**Comment by LaraMerdol** [comment]
This issue has been completed!
